export { WistMail } from './client.js'
export type {
  WistMailConfig,
  SendEmailParams,
  SendEmailResponse,
  BatchSendResponse,
  EmailStatus,
  EmailStatusResponse,
  Domain,
  DomainStatus,
  DomainVerification,
  DnsRecord,
  Template,
  TemplateVariable,
  CreateTemplateParams,
  UpdateTemplateParams,
  Webhook,
  WebhookEvent,
  CreateWebhookParams,
  UpdateWebhookParams,
  Audience,
  AudienceContact,
  CreateContactParams,
  UpdateContactParams,
  AnalyticsOverview,
  PaginatedResponse,
  PaginationParams,
  Attachment,
} from './types.js'
export {
  WistMailError,
  AuthenticationError,
  RateLimitError,
  ValidationError,
  NotFoundError,
} from './errors.js'
