// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMN9mK3VZFBzmDiqInZS3Pq6EG1D6ORqU',
    appId: '1:866414439480:android:fa6d14c7fd23f5f5618acd',
    messagingSenderId: '866414439480',
    projectId: 'wistfare-1756656058858',
    storageBucket: 'wistfare-1756656058858.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlPFBRyQje2RXEWFB2crTjsrSNFkV9bPg',
    appId: '1:866414439480:ios:d3d5b457f83daa03618acd',
    messagingSenderId: '866414439480',
    projectId: 'wistfare-1756656058858',
    storageBucket: 'wistfare-1756656058858.firebasestorage.app',
    androidClientId: '866414439480-iitnlckmg7jtbvd2jnh1f9hknlvb4b46.apps.googleusercontent.com',
    iosClientId: '866414439480-3tmsmc4702c77h17dq4b5f47870ira3h.apps.googleusercontent.com',
    iosBundleId: 'com.wistfare.wistmail',
  );
}
