export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  INBOX: '/inbox',
  SENT: '/sent',
  DRAFTS: '/drafts',
  STARRED: '/starred',
  SNOOZED: '/snoozed',
  SCHEDULED: '/scheduled',
  SPAM: '/spam',
  TRASH: '/trash',
  COMPOSE: '/compose',
  SEARCH: '/search',
  CONTACTS: '/contacts',
  ANALYTICS: '/analytics',
  TEMPLATES: '/templates',
  SETTINGS: '/settings',
  SETUP: '/setup',
} as const
